site:
  title: Antora Docs
  start_page: design::index.adoc
content:
  sources:
  - url: https://github.com/digitalubiquitycapital/design-phase-specs.git
    branches: [main]
    start_path: docs
ui:
  bundle:
    url: /home/inocult/projects/duc-docs/docs-ui-default/build/ui-bundle.zip
    snapshot: true
runtime:
  fetch: true
